// <auto-generated />
using System;
using FrontiereLiveGe.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrontiereLiveGe.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728133341_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("FrontiereLiveGe.Api.Models.AlertEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BorderPointId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPosted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PredictedDelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trend")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint");

                    b.HasIndex("BorderPointId", "CreatedAtUtc");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("FrontiereLiveGe.Api.Models.BorderPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BorderPoints");
                });

            modelBuilder.Entity("FrontiereLiveGe.Api.Models.BotSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriticalDelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinMinutesBetweenPosts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PostingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RisingThresholdMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("BotSettings");
                });

            modelBuilder.Entity("FrontiereLiveGe.Api.Models.TrafficSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BorderPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CongestionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstimatedDelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeedKmh")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BorderPointId", "RecordedAtUtc");

                    b.ToTable("TrafficSnapshots");
                });

            modelBuilder.Entity("FrontiereLiveGe.Api.Models.AlertEvent", b =>
                {
                    b.HasOne("FrontiereLiveGe.Api.Models.BorderPoint", "BorderPoint")
                        .WithMany("AlertEvents")
                        .HasForeignKey("BorderPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BorderPoint");
                });

            modelBuilder.Entity("FrontiereLiveGe.Api.Models.TrafficSnapshot", b =>
                {
                    b.HasOne("FrontiereLiveGe.Api.Models.BorderPoint", "BorderPoint")
                        .WithMany("TrafficSnapshots")
                        .HasForeignKey("BorderPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BorderPoint");
                });

            modelBuilder.Entity("FrontiereLiveGe.Api.Models.BorderPoint", b =>
                {
                    b.Navigation("AlertEvents");

                    b.Navigation("TrafficSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
